[colors]
[colors.primary]
background = "#0a0f1c"
foreground = "#d4d5d9"

[colors.normal]
black   = "#0a0f1c"
red     = "#869AAC"
green   = "#95A8B8"
yellow  = "#9FADB8"
blue    = "#9BB0C2"
magenta = "#A8B9C6"
cyan    = "#B8C7D0"
white   = "#d4d5d9"

[colors.bright]
black   = "#5f6374"
red     = "#869AAC"
green   = "#95A8B8"
yellow  = "#9FADB8"
blue    = "#9BB0C2"
magenta = "#A8B9C6"
cyan    = "#B8C7D0"
white   = "#d4d5d9"

[colors.cursor]
text   = "#0a0f1c"
cursor = "#d4d5d9"
