[colors]
[colors.primary]
background = "#170810"
foreground = "#ffffff"

[colors.normal]
black   = "#170810"
red     = "#E85F6F"
green   = "#F29B9A"
yellow  = "#D4A882"
blue    = "#D9A56C"
magenta = "#D1B399"
cyan    = "#E8C099"
white   = "#f0eaed"

[colors.bright]
black   = "#4a3c45"
red     = "#FF7A8A"
green   = "#FFB5B4"
yellow  = "#E6BA94"
blue    = "#EBB97E"
magenta = "#E3C5AB"
cyan    = "#FBD2AB"
white   = "#ffffff"

[colors.cursor]
text   = "#170810"
cursor = "#ffffff"
