[colors]
[colors.primary]
background = "#070707"
foreground = "#f5f5f5"

[colors.normal]
black   = "#070707"
red     = "#998f8f"
green   = "#978c8c"
yellow  = "#a59c9c"
blue    = "#b4acac"
magenta = "#c2bcbc"
cyan    = "#d1cccc"
white   = "#E8E8E8"

[colors.bright]
black   = "#d0cdcd"
red     = "#c5bfbf"
green   = "#afa7a7"
yellow  = "#bdb7b7"
blue    = "#ccc7c7"
magenta = "#dad7d7"
cyan    = "#e9e7e7"
white   = "#f5f5f5"

[colors.cursor]
text   = "#070707"
cursor = "#f5f5f5"
